### ISSUE TITLE
Nest account linking should be updated

### ISSUE THREAD

**Issue by pgattu** [exking/udi-nest2-poly#2]
I installed Nest2 node server.  The hyperlink shown on the node server configuration page to link to the Nest account points to the old Nest login page.  Google has converted the Nest accounts to Google accounts.  I tried to login with the old Nest account anyway, but I get the following error on the Nest website:

`Either your password is incorrect or you've migrated your account and need to sign in with Google.`

**Comment by exking** [comment]
Google has ended Works With Nest program, I don't think new accounts are allowed anymore...

**Comment by ClarkWalters** [comment]
Could you use the google linking method [chrisjshull](https://github.com/chrisjshull) used for homebridge: [homebridge-nest](https://github.com/chrisjshull/homebridge-nest/).

**Comment by exking** [comment]
not interested in unofficial integration..
