### ISSUE TITLE
NEST account upgraded by Google- now does not work

### ISSUE THREAD

**Issue by macjeff** [exking/udi-nest2-poly#3]
My nest account is now a google account.   I added smoke detectors and they made me upgrade and now the nodeserver wants me to re-authorize but wont take the account anymore.

Can you update the Auth?

**Comment by macjeff** [comment]
New api

https://developers.google.com/nest/device-access

**Comment by exking** [comment]
Currently I'm not planning on converting my account into a Google account in order to develop for the new API.

**Comment by macjeff** [comment]
Problem is they already said they are forcing everyone to convert this year and also if you add a new device or yours dies now they force you to convert.   I can see on their side they dont want to maintain two servers.
